"""Compatibility shim for historical ``from cognition.knowledge.backend import …``.

All implementation lives in :mod:`.schema`, :mod:`.ingest`, :mod:`.search`,
and :mod:`.lifecycle`. This module re-exports the public surface so existing
imports keep working during and after the split.
"""
from __future__ import annotations

from . import (
    EMBED_DIMS,
    KNOWLEDGE_CHUNK_CHARS,
    KNOWLEDGE_CONTEXT_CHARS,
    KNOWLEDGE_DB_PATH,
    KNOWLEDGE_ENTITY_BOOST,
    KNOWLEDGE_FTS_LIMIT,
    KNOWLEDGE_KNN_LIMIT,
    KNOWLEDGE_KNN_MIN_SIMILARITY,
    KNOWLEDGE_QUERY_INSTRUCT,
    KNOWLEDGE_RECALL_SCORE_THRESHOLD,
    KNOWLEDGE_RRF_K,
    KNOWLEDGE_SPREADING_ENABLED,
    KNOWLEDGE_SPREADING_MAX_EXTRA,
    KNOWLEDGE_SPREADING_SCORE_WEIGHT,
    KNOWLEDGE_SUPERSEDE_ON_DEDUP,
    KNOWLEDGE_WORKSPACE_DIR,
    KNOWLEDGE_WRITE_DEDUP_THRESHOLD,
    Embedder,
    KnowledgeIngest,
    KnowledgeLifecycle,
    KnowledgeSchema,
    KnowledgeSearch,
    KnowledgeStore,
    _connect,
    _ensure_knowledge_schema_migrated,
    _maybe_clear_knowledge_cache,
    _now,
    extract_text_from_file,
    ingest_file,
    ingest_text,
    ingest_workspace_knowledge_folder,
    knowledge_context_for,
    prune_knowledge,
    search_knowledge,
    vacuum_knowledge_db,
)

__all__ = [
    "KnowledgeStore",
    "KnowledgeSchema",
    "KnowledgeIngest",
    "KnowledgeSearch",
    "KnowledgeLifecycle",
    "Embedder",
    "extract_text_from_file",
    "ingest_file",
    "ingest_text",
    "ingest_workspace_knowledge_folder",
    "search_knowledge",
    "knowledge_context_for",
    "prune_knowledge",
    "vacuum_knowledge_db",
    "_connect",
    "_ensure_knowledge_schema_migrated",
    "_now",
    "_maybe_clear_knowledge_cache",
    "EMBED_DIMS",
    "KNOWLEDGE_DB_PATH",
    "KNOWLEDGE_CHUNK_CHARS",
    "KNOWLEDGE_CONTEXT_CHARS",
    "KNOWLEDGE_RRF_K",
    "KNOWLEDGE_KNN_LIMIT",
    "KNOWLEDGE_FTS_LIMIT",
    "KNOWLEDGE_RECALL_SCORE_THRESHOLD",
    "KNOWLEDGE_KNN_MIN_SIMILARITY",
    "KNOWLEDGE_QUERY_INSTRUCT",
    "KNOWLEDGE_WORKSPACE_DIR",
    "KNOWLEDGE_ENTITY_BOOST",
    "KNOWLEDGE_WRITE_DEDUP_THRESHOLD",
    "KNOWLEDGE_SUPERSEDE_ON_DEDUP",
    "KNOWLEDGE_SPREADING_ENABLED",
    "KNOWLEDGE_SPREADING_MAX_EXTRA",
    "KNOWLEDGE_SPREADING_SCORE_WEIGHT",
]
