const $ = (s) => document.querySelector(s);
const dialog = $('#editor'), form = $('#item-form'); let data = {items: [], schedules: []}, editing = null;
const text = (value) => value || 'No details yet';
const fmt = (value) => value ? new Intl.DateTimeFormat(undefined, {month:'short', day:'numeric', hour:'numeric', minute:'2-digit'}).format(new Date(value)) : '';
async function load(){ const response = await fetch('api/overview'); if (!response.ok) throw new Error('Could not load calendar'); data = await response.json(); render(); }
function render(){ const {brief} = data; $('#today').textContent = new Intl.DateTimeFormat(undefined,{weekday:'long',month:'long',day:'numeric'}).format(new Date(`${data.today}T12:00`)); $('#open-count').textContent=brief.open_count; $('#due-count').textContent=brief.due_today.length; $('#overdue-count').textContent=brief.overdue.length; $('#next-up').textContent=brief.next_up[0] ? `${brief.next_up[0].title}${brief.next_up[0].due_at ? ` · due ${fmt(brief.next_up[0].due_at)}` : ''}` : 'Nothing queued — make space for deep work.';
 const dated=data.items.filter(i=>i.kind==='appointment'||i.start_at).sort((a,b)=>new Date(a.start_at||a.due_at||0)-new Date(b.start_at||b.due_at||0)); $('#agenda-list').innerHTML=dated.length?dated.map(i=>`<article class="agenda-row" data-id="${i.id}"><b>${escapeHtml(i.title)}</b><small>${fmt(i.start_at||i.due_at)} · ${escapeHtml(i.project||i.kind)}</small></article>`).join(''):'<p class="empty">No appointments yet. Add time for what matters.</p>';
 $('#schedule-list').innerHTML=data.schedules.filter(s=>s.enabled!==false).length?data.schedules.filter(s=>s.enabled!==false).slice(0,6).map(s=>`<article class="schedule-row"><b>${escapeHtml(s.title)}</b><small>${s.frequency} · ${s.time_of_day} · ${escapeHtml(s.action||'announce')}</small></article>`).join(''):'<p class="empty">No active reminders or workflows.</p>';
 const groups=[['backlog','Backlog'],['todo','To do'],['doing','In progress'],['waiting','Waiting']]; $('#board-columns').innerHTML=groups.map(([status,label])=>`<section class="column"><h3>${label}</h3>${data.items.filter(i=>i.status===status).map(card).join('')}</section>`).join(''); document.querySelectorAll('[data-id]').forEach(el=>el.onclick=()=>openEditor(data.items.find(i=>i.id===el.dataset.id))); }
function card(i){return `<article class="card" data-id="${i.id}"><span class="tag">${escapeHtml(i.kind)} · ${escapeHtml(i.priority)}</span><p>${escapeHtml(i.title)}</p><small>${escapeHtml(i.project||text(i.due_at&&`Due ${fmt(i.due_at)}`))}</small></article>`} function escapeHtml(v){const d=document.createElement('div');d.textContent=v||'';return d.innerHTML}
function openEditor(item){editing=item||null; form.reset(); $('#modal-title').textContent=item?'Edit plan':'Plan an item'; $('#delete-item').hidden=!item; if(item) for(const [key,value] of Object.entries(item)){const field=form.elements[key];if(field&&value) field.value=(key.endsWith('_at')?value.slice(0,16):value)} dialog.showModal();}
$('#new-item').onclick=()=>openEditor(); $('#refresh').onclick=()=>load().catch(showError); $('#delete-item').onclick=async()=>{if(!editing||!confirm('Delete this plan and its linked reminder?'))return;await fetch(`api/items/${editing.id}`,{method:'DELETE'});dialog.close();load()};
form.onsubmit=async(e)=>{e.preventDefault();const fd=new FormData(form), payload=Object.fromEntries(fd.entries()); payload.schedule_enabled=undefined; if(fd.get('schedule_enabled')) payload.schedule={time_of_day:fd.get('schedule_time'),frequency:fd.get('schedule_frequency'),action:'announce'}; delete payload.schedule_time;delete payload.schedule_frequency;delete payload.schedule_enabled; for(const key of ['start_at','due_at']) if(!payload[key]) payload[key]=null; const response=await fetch(editing?`api/items/${editing.id}`:'api/items',{method:editing?'PUT':'POST',headers:{'Content-Type':'application/json'},body:JSON.stringify(payload)});if(!response.ok)return showError(await response.text());dialog.close();load()}; function showError(err){alert(typeof err==='string'?err:err.message)} load().catch(showError);
