services:
  searxng:
    image: searxng/searxng:2026.5.31-300695de5
    container_name: aiko_searxng
    restart: unless-stopped
    ports:
      - "8081:8080"
    volumes:
      - ./searxng:/etc/searxng
    env_file:
      - .env
    environment:
      - SEARXNG_BASE_URL=http://localhost:8081
      - SEARXNG_SECRET=${SEARXNG_SECRET}
