"""Public memory API façade.

Most implementation details live in focused modules.  This module keeps the
stable import path used by the rest of the application:

    from cognition.memory.memorize import AikoMemorize, format_for_context, infer_valence_score
"""

from __future__ import annotations

from .backend import (
    AikoMemorize,
    BOOT_LABELS,
    EMBED_DIMS,
    MEMORY_LIFECYCLE_BATCH_SIZE,
    MEMORY_RECALL_SCORE_THRESHOLD,
    MEMORY_RECENCY_RERANK_THRESHOLD,
    MEMORY_SEARCH_CACHE_TTL,
    MEMORY_WRITE_IDLE_GRACE,
    MEMORY_WRITE_MAX_WAIT,
    PERSONA_CACHE_TTL,
    WRITE_DEDUP_THRESHOLD,
    _MemoryBackend,
    _PHASE_A_COLUMNS,
    _first_json_array,
    _is_trivial_input,
    _normalize_memory_text,
    _sanitize_fts_query,
    backfill_entities,
    classify_kind,
    classify_write_op,
    entities_from_json,
    entities_to_json,
    entity_overlap_score,
    ensure_entity_relations_schema,
    ensure_l2_scene_schema,
    ensure_phase_a_schema,
    existing_columns,
    extract_entities,
    infer_salience_hit,
    infer_valence_score,
    infer_valence_tag,
    normalize_memory_text,
    rebuild_entity_relations,
    SALIENCE_POLICY_RE,
    tag_from_score,
    upsert_co_mentions,
    vacuum_memory_db,
)

format_for_context = AikoMemorize.format_for_context

__all__ = [
    "AikoMemorize",
    "BOOT_LABELS",
    "EMBED_DIMS",
    "MEMORY_LIFECYCLE_BATCH_SIZE",
    "MEMORY_RECALL_SCORE_THRESHOLD",
    "MEMORY_RECENCY_RERANK_THRESHOLD",
    "MEMORY_SEARCH_CACHE_TTL",
    "MEMORY_WRITE_IDLE_GRACE",
    "MEMORY_WRITE_MAX_WAIT",
    "PERSONA_CACHE_TTL",
    "WRITE_DEDUP_THRESHOLD",
    "_MemoryBackend",
    "_PHASE_A_COLUMNS",
    "_first_json_array",
    "_is_trivial_input",
    "_normalize_memory_text",
    "_sanitize_fts_query",
    "backfill_entities",
    "classify_kind",
    "classify_write_op",
    "entities_from_json",
    "entities_to_json",
    "entity_overlap_score",
    "ensure_entity_relations_schema",
    "ensure_l2_scene_schema",
    "ensure_phase_a_schema",
    "existing_columns",
    "extract_entities",
    "format_for_context",
    "infer_salience_hit",
    "infer_valence_score",
    "infer_valence_tag",
    "normalize_memory_text",
    "rebuild_entity_relations",
    "SALIENCE_POLICY_RE",
    "tag_from_score",
    "upsert_co_mentions",
    "vacuum_memory_db",
]
