use_default_settings: true

server:
  secret_key: "change-me"
  limiter: false
  image_proxy: false
  method: "GET"

search:
  safe_search: 0
  autocomplete: ""
  default_lang: "en"
  formats:
    - html
    - json

outgoing:
  request_timeout: 5.0
  pool_connections: 10
  pool_maxsize: 5
  enable_http2: false

engines:
  - name: google
    engine: google
    shortcut: go
    disabled: false

  - name: duckduckgo
    engine: duckduckgo
    shortcut: ddg
    disabled: false

  - name: brave
    engine: brave
    shortcut: br
    brave_category: search
    disabled: false

  - name: wikipedia
    engine: wikipedia
    shortcut: wp
    display_type: ["infobox"]
    disabled: false
